import {
	getEnviromentVariablesObject,
	prepareEnvironmentVariablesForShell,
} from "@dokploy/server/utils/docker/utils";
import { quote } from "shell-quote";
import {
	getBuildAppDirectory,
	getDockerContextPath,
} from "../filesystem/directory";
import type { ApplicationNested } from ".";
import { createEnvFileCommand } from "./utils";

/**
 * Detects if the `dockerfile` field contains inline Dockerfile content
 * rather than a filename/path. Returns true if it looks like content.
 */
const isInlineDockerfileContent = (dockerfile: string | null): boolean => {
	if (!dockerfile) return false;
	return dockerfile.includes("\n") || dockerfile.startsWith("FROM ");
};

export const getDockerCommand = (application: ApplicationNested) => {
	const {
		appName,
		env,
		publishDirectory,
		buildArgs,
		buildSecrets,
		dockerBuildStage,
		cleanCache,
		createEnvFile,
	} = application;

	// If the dockerfile field contains inline content (generated by the wizard),
	// we need to write it to a file and use the file path instead.
	const hasInlineDockerfile = isInlineDockerfileContent(application.dockerfile);

	const effectiveApplication = hasInlineDockerfile
		? { ...application, dockerfile: "Dockerfile" }
		: application;

	const dockerFilePath = getBuildAppDirectory(effectiveApplication);

	try {
		const image = `${appName}`;

		const defaultContextPath =
			dockerFilePath.substring(0, dockerFilePath.lastIndexOf("/") + 1) || ".";

		const dockerContextPath =
			getDockerContextPath(application) || defaultContextPath;

		const commandArgs = ["build", "-t", image, "-f", dockerFilePath, "."];

		if (dockerBuildStage) {
			commandArgs.push("--target", dockerBuildStage);
		}

		if (cleanCache) {
			commandArgs.push("--no-cache");
		}

		const args = prepareEnvironmentVariablesForShell(
			buildArgs,
			application.environment.project.env,
			application.environment.env,
		);

		for (const arg of args) {
			commandArgs.push("--build-arg", arg);
		}

		const secrets = getEnviromentVariablesObject(
			buildSecrets,
			application.environment.project.env,
			application.environment.env,
		);

		const joinedSecrets = Object.entries(secrets)
			.map(([key, value]) => `${key}=${quote([value])}`)
			.join(" ");

		/*
			Do not generate an environment file when publishDirectory is specified,
			as it could be publicly exposed.
			Also respect the createEnvFile flag.
		*/
		let command = "";
		if (!publishDirectory && createEnvFile) {
			command += createEnvFileCommand(
				dockerFilePath,
				env,
				application.environment.project.env,
				application.environment.env,
			);
		}

		for (const key in secrets) {
			// Although buildx is smart enough to know we may be referring to an environment variable name,
			// we still make sure it doesn't fall back to `type=file`.
			// See: https://docs.docker.com/reference/cli/docker/buildx/build/#secret
			commandArgs.push("--secret", `type=env,id=${key}`);
		}

		// If we have inline Dockerfile content, write it to the expected file path
		if (hasInlineDockerfile && application.dockerfile) {
			const base64Content = Buffer.from(application.dockerfile).toString("base64");
			command += `
echo "Writing generated Dockerfile to ${dockerFilePath}" ;
mkdir -p "$(dirname "${dockerFilePath}")" ;
echo "${base64Content}" | base64 -d > "${dockerFilePath}" ;
`;
		}

		command += `
echo "Building ${appName}" ;
cd ${dockerContextPath} || { 
  echo "❌ The path ${dockerContextPath} does not exist" ;
  exit 1;
}

${joinedSecrets} docker ${commandArgs.join(" ")} || { 
  echo "❌ Docker build failed" ;
  exit 1;
}
echo "✅ Docker build completed." ;
		`;

		return command;
	} catch (error) {
		throw error;
	}
};
